import React, {useEffect, useMemo, useState} from 'react';
import {Routes, Route, Link, NavLink, useLocation, useNavigate} from 'react-router-dom';
import { wedding, schedule, gallery, coloradoQuestions, weddingParty, thankYou, receptionMenu, weekend, tablePlaces, seatingChart, guestFaq } from './data';

const nav = [['/','Home'],['/schedule','Schedule'],['/passport','Passport'],['/directions','Directions'],['/more','More']];
const navIcons={'/':'⌂','/schedule':'◷','/passport':'✦','/directions':'⌖','/more':'☰'};
const menuGroups = [
  ['Wedding Day', [['/know-before-you-go','Know Before You Go'],['/schedule','Schedule'],['/weekend','Wedding Weekend'],['/ceremony','Ceremony'],['/reception','Reception'],['/directions','Directions'],['/weather-parking','Weather + Parking']]],
  ['Celebrate', [['/passport','Wedding Passport'],['/honeymoon','Costa Rica 🌴'],['/drinks','Signature Drinks'],['/kids','Junior Wedding Explorers'],['/tables','Find My Table'],['/messages','Messages of Love'],['/gifts','Gifts & Well Wishes'],['/snack','Late-Night Snack'],['/thank-you','A Note From Us']]],
  ['Our People', [['/family','Our Crew'],['/wedding-party','Our People']]],
];
const stampLabels=['Mountain Morning','City Celebration','Captured a Moment','Left a Message','Trivia Master','Met the Crew','Cheers','Dancing Queen'];

function denverClock(date=new Date()){
  const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
  return {year:+parts.year,month:+parts.month,day:+parts.day,hour:+parts.hour,minute:+parts.minute,minutes:(+parts.hour)*60+(+parts.minute)};
}
function isWeddingDayDenver(date=new Date()){const d=denverClock(date);return d.year===2026&&d.month===9&&d.day===28}
function parseEventMinutes(label=''){const m=label.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);if(!m)return null;let h=(+m[1])%12+(m[3].toUpperCase()==='PM'?12:0);return h*60+(+m[2])}

function Layout({children}){
  const loc=useLocation();
  const navigate=useNavigate();
  const [menuOpen,setMenuOpen]=useState(false);
  const [largeText,setLargeText]=useState(()=>localStorage.getItem('wg-large-text')==='1');
  const [guestAlert,setGuestAlert]=useState(null);
  const [online,setOnline]=useState(()=>navigator.onLine);
  const [installPrompt,setInstallPrompt]=useState(null);
  const isHome=loc.pathname==='/';
  useEffect(()=>{window.scrollTo({top:0, behavior:'instant'});setMenuOpen(false)},[loc.pathname]);
  useEffect(()=>{document.body.style.overflow=menuOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[menuOpen]);
  useEffect(()=>{document.documentElement.classList.toggle('large-text',largeText);localStorage.setItem('wg-large-text',largeText?'1':'0')},[largeText]);
  useEffect(()=>{let alive=true;fetch('/.netlify/functions/public-config',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(x=>{if(alive&&x?.message)setGuestAlert(x)}).catch(()=>{});return()=>{alive=false}},[]);
  useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);
  useEffect(()=>{const handler=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler)},[]);
  const installApp=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)};
  const goBack=()=>{if(isHome)return;loc.key==='default'?navigate('/'):navigate(-1)};
  return <div className="app-shell">
    <header className="site-header">
      <div className="site-header-inner">
        {isHome?<span className="brand-mark" aria-hidden="true">C&amp;M</span>:<button className="header-action back-action" onClick={goBack} aria-label="Go back">← Back</button>}
        <Link to="/" className="header-title" aria-label="Cory and Melinda wedding hub home"><b>Cory &amp; Melinda</b><small>09 · 28 · 26</small></Link>
        <button className="header-action menu-action" onClick={()=>setMenuOpen(true)} aria-expanded={menuOpen} aria-controls="site-menu">Menu <span aria-hidden="true">☰</span></button>
      </div>
    </header>
    {guestAlert&&<div className="guest-alert" role="status"><div><b>Wedding Day Update</b><span>{guestAlert.message}</span></div>{guestAlert.link&&<a href={guestAlert.link} target="_blank" rel="noreferrer">Details</a>}<button aria-label="Dismiss update" onClick={()=>setGuestAlert(null)}>×</button></div>}
    {!online&&<div className="offline-banner">Offline mode · saved Wedding Hub pages are still available</div>}
    <main className="route-main"><div key={loc.pathname} className="route-view">{children}</div></main>
    <nav className="bottom-nav" aria-label="Quick navigation">
      {nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/'} className={({isActive})=>isActive?'active':''}><span className="nav-icon" aria-hidden="true">{navIcons[to]}</span><span>{label}</span></NavLink>)}
    </nav>
    {menuOpen&&<div className="menu-layer"><button className="menu-scrim" aria-label="Close menu" onClick={()=>setMenuOpen(false)}/><aside id="site-menu" className="menu-drawer" aria-label="Wedding hub menu"><div className="menu-head"><div><span className="menu-eyebrow">#FinallyGenerlette</span><h2>Wedding Hub</h2></div><button className="menu-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu">×</button></div>{menuGroups.map(([group,items])=><section className="menu-group" key={group}><h3>{group}</h3><div>{items.map(([to,label])=><NavLink key={to} to={to} className={({isActive})=>isActive?'menu-current':''}>{label}<span aria-hidden="true">›</span></NavLink>)}</div></section>)}<button className="text-size-toggle" onClick={()=>setLargeText(v=>!v)}>{largeText?'Standard text':'Larger text'} <span aria-hidden="true">Aa</span></button>{installPrompt&&<button className="text-size-toggle install-app" onClick={installApp}>Install Wedding Hub <span aria-hidden="true">＋</span></button>}<span className="connection-status">{online?'Ready for offline use':'Offline mode active'}</span><NavLink className="team-menu-link" to="/day-of">Wedding team access <span aria-hidden="true">🔒</span></NavLink></aside></div>}
  </div>
}

const SectionTitle=({eyebrow,title,sub})=><header className="section-title"><span>{eyebrow}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}<div className="gold-heart">— ♥ —</div></header>;
const Card=({children,className=''})=><div className={'card '+className}>{children}</div>;
const External=({href,children,className=''})=><a className={'button '+className} href={href} target="_blank" rel="noreferrer">{children}</a>;
const AppLink=({to,children,className=''})=><Link className={'button '+className} to={to}>{children}</Link>;

function Home(){
  const now=new Date();
  const afterWedding=now>=new Date('2026-09-29T00:00:00-06:00');
  return <>
    <section className="hero" style={{backgroundImage:"linear-gradient(180deg,rgba(6,31,54,.18),rgba(6,31,54,.78)),url('/images/IMG_5958.jpg')"}}>
      <div className="hero-copy"><span className="kicker">SEPTEMBER 28, 2026</span><h1>Cory <em>&</em> Melinda</h1><p>{afterWedding?'We did it — now the adventure continues.':'A mountain day. A lifetime to celebrate.'}</p><Countdown/></div>
    </section>
    <section className="page"><Card className="honeymoon-banner home-honeymoon"><span className="badge">{afterWedding?'NEXT ADVENTURE':'AFTER “I DO”'}</span><h3>Colorado mountains → Costa Rica palms 🌴</h3><p>{weekend.honeymoon.publicNote}</p><div className="actions"><AppLink to="/honeymoon">Our next adventure</AppLink>{afterWedding&&<External href={wedding.links.disposableCamera} className="secondary">Share wedding photos</External>}</div></Card></section>
    <section className="page quick-grid three">
      <External href={wedding.links.disposableCamera} className="feature-btn camera"><b>📸 Disposable Camera</b><small>Capture the night · {wedding.hashtag}</small></External>
      <External href={wedding.links.audioGuestbook} className="feature-btn phone"><b>☎️ Leave a Voice Message</b><small>Say something sweet, funny, or unforgettable</small></External>
      <AppLink to="/messages" className="feature-btn note"><b>💌 Write Us a Note</b><small>Sweet, funny, ridiculous or wise</small></AppLink>
    </section>
    <section className="page"><NowCard/></section>
    <section className="mountain-divider"><div><span>COLORADO WEDDING ADVENTURE</span><b>From the ceremony view to the dance floor</b></div></section>
    <section className="page"><Gallery/></section>
    <section className="page"><ColoradoQuiz compact/></section>
    <section className="page"><SectionTitle eyebrow="Explore" title="Everything in one place"/><div className="tile-grid">
      {[["/know-before-you-go","Know Before You Go","Parking, layers, travel, seating & guest FAQs"],["/weekend","Wedding Weekend","Rehearsal evening + what happens next"],["/ceremony","The Ceremony","Mountain parking, order & what to expect"],["/reception","The Reception","Dinner menu, timing, drinks & dancing"],["/honeymoon","Costa Rica 🌴","Our next adventure after the wedding"],["/family","Our Crew","Miah, Londyn & family adventures"],["/wedding-party","Our People","Parents and wedding party"],["/messages","Messages of Love","Write a note or leave us a voice message"],["/gifts","Gifts & Well Wishes","Costa Rica honeymoon fund"],["/kids","Junior Wedding Explorers","A real-world wedding adventure challenge"],["/weather-parking","Weather + Parking","Live event forecast & how to pay"],["/drinks","Something Old + Blue","Signature drinks and dessert"]].map(([to,t,d])=><Link to={to} className="info-tile" key={to}><b>{t}</b><span>{d}</span></Link>)}
    </div></section>
  </>
}

function Countdown(){
  const [now,setNow]=useState(new Date()); useEffect(()=>{const t=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(t)},[]);
  const target=new Date('2026-09-28T15:30:00-06:00'); const end=new Date('2026-09-29T00:00:00-06:00'); const days=Math.max(0,Math.ceil((target-now)/86400000));
  return <div className="countdown">{now>=end?<b>Just married ✨</b>:isWeddingDayDenver(now)?<b>Happening Today ✨</b>:<><strong>{days}</strong><span>days to go</span></>}</div>
}

function NowCard(){
  const [now,setNow]=useState(new Date()); useEffect(()=>{const t=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(t)},[]);
  const weddingDay=isWeddingDayDenver(now);
  let current=null,next=null;
  if(weddingDay){const mins=denverClock(now).minutes;for(let i=0;i<schedule.length;i++){const t=parseEventMinutes(schedule[i][0]);if(t===null)continue;if(t<=mins)current=schedule[i];else{next=schedule[i];break}}}
  return <Card className="now-card paper-card"><span className="badge">{weddingDay?'HAPPENING NOW · DENVER TIME':'WEDDING DAY'}</span><h3>{weddingDay?(current?.[1]||'Wedding day is underway!'):'What’s happening?'}</h3><p>{weddingDay?(current?.[2]||'Open the full schedule for the next cue.'):'On September 28 this card will automatically show what is happening now and what comes next in Colorado time.'}</p>{weddingDay&&next&&<p className="tiny"><b>Next:</b> {next[0]} · {next[1]}</p>}<AppLink to="/schedule">Open the day-of schedule</AppLink></Card>
}

function Gallery(){return <><SectionTitle eyebrow="Favorite Moments" title="Mountain memories, adventures & our crew" sub="A little photo scrapbook — swipe on your phone."/><div className="filmstrip">{gallery.map(([src,cap],i)=><figure className={'polaroid p'+(i%3)} key={src}><img src={'/images/'+src} alt={`Cory and Melinda photo ${i+1}`} loading="lazy" decoding="async" fetchPriority="low"/><figcaption>{cap}</figcaption></figure>)}</div></>}

function SchedulePage(){
  const [now,setNow]=useState(new Date()); useEffect(()=>{const t=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(t)},[]);
  const weddingDay=isWeddingDayDenver(now);
  let current=-1;if(weddingDay){const mins=denverClock(now).minutes;schedule.forEach((x,i)=>{const t=parseEventMinutes(x[0]);if(t!==null&&t<=mins)current=i})}
  return <><PageHero title="Wedding Day Schedule" sub="Monday · September 28, 2026"><AppLink to="/know-before-you-go" className="secondary">Know before you go</AppLink></PageHero><section className="page"><div className="timeline itinerary">{schedule.map((s,i)=><div key={s[0]+s[1]} className={'timeline-row '+(i===current?'current':'')}><time>{s[0]}</time><div><h3>{s[1]}</h3>{s[2]&&<p>{s[2]}</p>}</div></div>)}</div><div className="actions"><AppLink to="/ceremony">Ceremony details</AppLink><AppLink to="/reception" className="secondary">Reception details</AppLink></div></section></>
}

function PageHero({title,sub,children}){return <section className="mini-hero"><span>— ♥ —</span><h1>{title}</h1>{sub&&<p>{sub}</p>}{children}</section>}

function downloadCalendar({title,start,end,location,description=''}){const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Cory and Melinda Wedding//EN','BEGIN:VEVENT',`DTSTART;TZID=America/Denver:${start}`,`DTEND;TZID=America/Denver:${end}`,`SUMMARY:${title}`,`LOCATION:${location}`,`DESCRIPTION:${description}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/calendar'}));a.download=title.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function CalendarButton({kind}){const ev=kind==='ceremony'?{title:'Cory & Melinda Wedding Ceremony',start:'20260928T153000',end:'20260928T160500',location:'Sunrise Amphitheater, Boulder, Colorado',description:'Cory & Melinda · #FinallyGenerlette'}:{title:'Cory & Melinda Wedding Reception',start:'20260928T170000',end:'20260928T230000',location:'City Park Pavilion, 2001 Steele Street, Denver, CO 80206',description:'Cocktail hour begins at 5:00 PM.'};return <button className="button secondary" onClick={()=>downloadCalendar(ev)}>Add to calendar</button>}

function ImageLightbox({src,alt,caption,className=''}){const [open,setOpen]=useState(false);return <><button type="button" className={'image-button '+className} onClick={()=>setOpen(true)} aria-label={`Enlarge ${alt}`}><img src={src} alt={alt} loading="lazy" decoding="async"/>{caption&&<span>{caption}</span>}</button>{open&&<div className="lightbox" role="dialog" aria-modal="true" aria-label={alt}><button className="lightbox-scrim" aria-label="Close image" onClick={()=>setOpen(false)}/><div className="lightbox-panel"><button className="lightbox-close" onClick={()=>setOpen(false)} aria-label="Close">×</button><img src={src} alt={alt}/>{caption&&<p>{caption}</p>}</div></div>}</>}

function KnowBeforeYouGo(){return <><PageHero title="Know Before You Go" sub="The practical stuff, all in one place"/><section className="page"><Card className="paper-card faq-intro"><span className="badge">MONDAY · SEPTEMBER 28</span><h3>Mountain ceremony → Denver reception</h3><p>Save this page before you head out. It brings together the questions we would rather answer here than from the aisle. 💙</p><div className="actions"><AppLink to="/directions">Directions</AppLink><AppLink to="/weather-parking" className="secondary">Weather + parking</AppLink><AppLink to="/tables" className="secondary">Find my table</AppLink></div></Card><div className="faq-list">{guestFaq.map(([q,a],i)=><details className="faq-item" key={q} open={i===0}><summary>{q}<span aria-hidden="true">＋</span></summary><p>{a}</p></details>)}</div><Card className="mountain-note"><span className="badge">QUICK REMINDER</span><h3>Before driving up Flagstaff Road</h3><p>Open your directions, handle parking, bring a layer and give yourself more time than you think you need. The mountain is beautiful; rushing up it is not.</p></Card></section></>}

function WeddingWeekend(){return <><PageHero title="Wedding Weekend" sub="A little Colorado time together before the big day"/><section className="page"><Card><span className="badge">SUNDAY · SEPTEMBER 27 · REHEARSAL EVENING</span><h3>Wedding party + family</h3><p>This rehearsal is intended for the people participating in the ceremony. If you were invited to the rehearsal, here’s the plan:</p><div className="private-timeline public-weekend">{weekend.rehearsal.map(x=><div key={x.time}><time>{x.time}</time><div><b>{x.title}</b><span>{x.note}</span></div></div>)}</div></Card><Card className="honeymoon-banner"><span className="badge">AFTER THE WEDDING</span><h3>Next stop: Costa Rica 🌴</h3><p>{weekend.honeymoon.publicNote}</p><p className="tiny">We’re keeping exact travel logistics private — but yes, it is a very quick turnaround after the glow-stick send-off.</p></Card><Card><h3>Need the wedding-day details?</h3><div className="actions"><AppLink to="/schedule">Wedding-day schedule</AppLink><AppLink to="/directions" className="secondary">Directions</AppLink></div></Card></section></>}

function Honeymoon(){return <><PageHero title="Next Adventure: Costa Rica 🌴" sub="From Colorado mountains to palm trees"/><section className="page"><Card className="honeymoon-banner honeymoon-feature"><span className="badge">THE MORNING AFTER</span><h3>We’re heading to Costa Rica!</h3><p>{weekend.honeymoon.publicNote}</p><p>After the ceremony, dinner, dancing and glow-stick send-off, our next chapter starts almost immediately. We’ll be swapping mountain air for warm beaches, rainforest adventures and a little newlywed time together.</p><p className="tiny">We’re keeping our exact flight and travel details private, but the turnaround is definitely quick. ☕✈️🌴</p></Card><div className="two-col"><Card><h3>Want to send us off with a memory?</h3><p>Leave a written note, voice message or wedding-day photo for us to enjoy after the whirlwind.</p><div className="actions"><AppLink to="/messages">Leave us a message</AppLink><External href={wedding.links.disposableCamera} className="secondary">Share a photo</External></div></Card><Card><h3>Costa Rica Honeymoon Fund</h3><p>No gift is expected. For friends and family who have asked, our honeymoon contribution option is tucked into Gifts & Well Wishes.</p><AppLink to="/gifts">Gifts & Well Wishes</AppLink></Card></div></section></>}

function Ceremony(){return <><PageHero title="The Ceremony" sub="Sunrise Amphitheater · 3:30 PM"><CalendarButton kind="ceremony"/></PageHero><section className="page two-col"><Card><h3>Ceremony flow</h3><ol className="pretty-list">{['Processional','Welcome','Opening reflection / blessing to everyone','Rose presentation to mothers','Traditional vows','Ring exchange','Family joining ceremony with Miah & Londyn + Daughter charms','Pronouncement & kiss','Final blessing','Recessional'].map(x=><li key={x}>{x}</li>)}</ol></Card><ParkingCard/><Card><span className="badge">BEFORE YOU HEAD UP THE MOUNTAIN</span><h3>Quick guest checklist</h3><ul><li>Pay the Flagstaff Mountain parking permit before driving up if your vehicle is not registered in Boulder County.</li><li>Open your directions before climbing Flagstaff Road in case cell service gets spotty.</li><li>Bring a light layer — mountain temperatures can change quickly.</li><li>Wear shoes you are comfortable walking in around the amphitheater.</li><li>Use the restroom before lineup if needed; Sunrise has pit-latrine facilities only.</li><li>Charge your phone for photos, the disposable-camera link and directions to Denver afterward.</li></ul></Card></section></>}
function Reception(){return <><PageHero title="The Reception" sub="Cocktail hour 5:00 PM · Grand entrance 6:00 PM · Denver"><CalendarButton kind="reception"/></PageHero><section className="page"><Card className="menu-card"><span className="badge">DINNER MENU</span><h3>Come hungry 🍽️</h3><div className="menu-columns"><div><h4>Italian favorites</h4><ul>{receptionMenu.italian.map(x=><li key={x}>{x}</li>)}</ul></div><div><h4>Jamaican favorites <small className="menu-pending">final caterer confirmation pending</small></h4><ul>{receptionMenu.jamaican.map(x=><li key={x}>{x}</li>)}</ul></div></div><p className="tiny">{receptionMenu.cocktail}</p><p>{receptionMenu.dessert}</p></Card><Card><h3>A few surprises are staying secret ✨</h3><p>We’ll share the timing, food and what guests need to know — but we’re saving a couple of reception moments for the room.</p></Card><div className="timeline compact">{schedule.slice(5).map(s=><div className="timeline-row" key={s[0]+s[1]}><time>{s[0]}</time><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></section></>}

function Directions(){return <><PageHero title="Directions" sub="Two stops. One very good day."/><section className="page two-col"><VenueCard kind="Ceremony" data={wedding.ceremony}/><VenueCard kind="Reception" data={wedding.reception}/></section></>}
function VenueCard({kind,data}){const q=encodeURIComponent(data.mapsQuery);return <Card><span className="badge">{kind}</span><h3>{data.name}</h3><p>{data.address||data.city}</p><div className="actions"><External href={`https://maps.google.com/?q=${q}`}>Google Maps</External><External href={`https://maps.apple.com/?q=${q}`} className="secondary">Apple Maps</External></div></Card>}

function ParkingCard(){return <Card className="parking"><span className="badge">FLAGSTAFF MOUNTAIN PARKING</span><h3>Pay before you head up</h3><p>Vehicles <b>not registered in Boulder County</b> need a <b>$5 daily OSMP permit</b>.</p><ul><li>ParkMobile zone: <b>24700</b></li><li>Pay in the ParkMobile app/web, or at self-service stations with exact cash/check.</li><li>Sunrise Amphitheater has about <b>10 regular + 3 ADA</b> spaces; parking is not guaranteed.</li><li>Flagstaff Road has a <b>30-foot vehicle-length limit</b>; shuttle parking is not guaranteed.</li><li>Cell service can be spotty, so paying before driving up is smart. Carpooling is strongly encouraged.</li></ul><div className="actions"><External href={wedding.links.parkMobile}>Open ParkMobile</External><External href={wedding.links.boulderParking} className="secondary">Official Boulder info</External></div></Card>}

function Passport(){const [name,setName]=useState(()=>localStorage.getItem('wg-name')||'');const [stamps,setStamps]=useState(()=>JSON.parse(localStorage.getItem('wg-stamps')||'[]'));const [draft,setDraft]=useState(name);useEffect(()=>{localStorage.setItem('wg-stamps',JSON.stringify(stamps))},[stamps]);const toggle=i=>setStamps(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i]);
  if(!name)return <><PageHero title="Wedding Passport" sub="Collect 8 stamps. Unlock extras, snacks & bragging rights."/><section className="page"><Card className="passport-start"><label>Your name or nickname<input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="e.g., Aunt Lisa"/></label><button className="button" disabled={!draft.trim()} onClick={()=>{setName(draft.trim());localStorage.setItem('wg-name',draft.trim())}}>Start Collecting</button></Card></section></>;
  return <><PageHero title={`${name}’s Wedding Passport`} sub={`${stamps.length}/8 stamps collected`}/><section className="page"><div className="progress"><span style={{width:`${stamps.length/8*100}%`}}/></div><div className="stamp-grid">{stampLabels.map((x,i)=><button className={'stamp '+(stamps.includes(i)?'earned':'')} onClick={()=>toggle(i)} key={x}><span>{stamps.includes(i)?'✓':'○'}</span><b>{x}</b></button>)}</div><div className="unlock-grid"><Card className={stamps.length>=4?'unlocked':'locked'}><b>4 stamps · Meet Our Crew</b><p>{stamps.length>=4?'Unlocked!':'Keep collecting…'}</p>{stamps.length>=4&&<AppLink to="/family">Meet the crew</AppLink>}</Card><Card className={stamps.length>=6?'unlocked':'locked'}><b>6 stamps · Karaoke Energy</b><p>{stamps.length>=6?'Unlocked: Cory & Melinda have taken the mic together twice. 🎤':'Locked'}</p></Card><Card className={stamps.length>=7?'unlocked':'locked'}><b>7 stamps · Snack Secret</b>{stamps.length>=7?<><p>Late-night snacks arrive at <b>9:30 PM</b>. Head to the snack station and refuel before the final dance-floor stretch.</p></>:<p>Locked</p>}</Card></div>{stamps.length===8&&<div className="complete">🏔️ PASSPORT COMPLETE 🏔️<small>Show Cory or Melinda for a high-five.</small></div>}</section></>
}


function Family(){return <><PageHero title="Our Crew" sub="The family at the heart of the celebration"/><section className="page"><div className="family-hero"><img src="/images/IMG_1089.jpg" alt="Cory, Melinda, Miah and Londyn in the Colorado mountains" loading="lazy" decoding="async"/></div><div className="family-photo-grid"><img src="/images/IMG_3342.jpg" alt="Family Colorado adventure" loading="lazy" decoding="async"/><img src="/images/IMG_4258.jpg" alt="Family fall day together" loading="lazy" decoding="async"/><img src="/images/CRI_9149.jpg" alt="Family outdoor adventure" loading="lazy" decoding="async"/><img src="/images/IMG_6754.jpg" alt="Family holiday memory" loading="lazy" decoding="async"/></div><div className="two-col"><Card><h3>Londyn</h3><p>Rock climbing 🧗 · anime 🎬 · mountain adventure energy</p></Card><Card><h3>Miah</h3><p>Golf ⛳ · family adventure energy</p></Card></div><p className="center-note">Miah and Londyn love Cory, and this celebration is about the family all four of them are building together.</p></section></>}

function WeddingParty(){const any=[...weddingParty.parents,...weddingParty.party].some(x=>x.name||x.names);const fun={"Maid / Matron of Honor":"Melinda’s right hand for the big day.","Bridesmaids + Daughters":"The daughters at the heart of this whole family story.","Bridesman + Bride’s Brother":"Brother duties, wedding-party duties, and keeping things moving.","Best Man":"Cory’s best-man backup and reception-toast representative.","Groomsman":"Part of Cory’s crew and ready for the processional.","Groomswomen + Groom’s Sisters":"Cory’s sisters — family, wedding party and lifelong witnesses to the story.","Junior Bridesmaid":"A very important member of the aisle crew.","Ring Bearer":"Tiny title. Extremely important cargo.","Flower Girls":"Three individual entrances and maximum flower-girl energy."};return <><PageHero title="Our People" sub="Parents, wedding party & the people standing beside us"/><section className="page"><Card><h3>Parents & family</h3>{weddingParty.parents.map(x=><div className="role-row people-row" key={x.role}><div><b>{x.role}</b><small>{x.role.includes('Officiant')?'Cory’s dad will also lead the ceremony.':'Family at the heart of the day.'}</small></div><span>{x.names||'Name coming soon'}</span></div>)}</Card><Card><h3>Wedding party</h3>{weddingParty.party.map(x=><div className="role-row people-row" key={x.role}><div><b>{x.role}</b><small>{fun[x.role]||'Standing beside Cory & Melinda.'}</small></div><span>{x.name||'Name coming soon'}</span></div>)}</Card>{!any&&<p className="center-note">The structure is ready — add names in the wedding data file before publishing.</p>}</section></>}
function ThankYou(){return <><PageHero title="A Note From Us" sub="To everyone celebrating with us"/><section className="page"><Card className="letter"><div className="gold-heart">— ♥ —</div><p>{thankYou}</p><strong>With all our love,<br/>Cory & Melinda</strong></Card></section></>}

function Drinks(){return <><PageHero title="Treat Yourself" sub="Something old, something blue & something sweet"/><section className="page drink-grid"><img src="/images/something-old.webp" alt="Something Old — Old Fashioned sign" loading="lazy" decoding="async"/><img src="/images/something-blue.webp" alt="Something Blue — Blue Skies sign" loading="lazy" decoding="async"/><img src="/images/desserts-sign.webp" alt="Desserts — treat yourself sign" loading="lazy" decoding="async"/></section></>}

function WeatherParking(){return <><PageHero title="Weather + Parking" sub="Plan the mountain ceremony and Denver evening"/><section className="page"><WeatherCards/><ParkingCard/><Card><span className="badge">RECEPTION PARKING</span><h3>City Park Pavilion</h3><p>Use designated parking spaces or other legal parking areas and follow posted signs. We have not found an official special event parking fee for the Pavilion itself, so the app does not claim one.</p></Card></section></>}

const codeText={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorms'};
function WeatherCards(){
  const [data,setData]=useState({loading:true});
  useEffect(()=>{let alive=true;async function run(){const cacheKey='wg-weather-v2';try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<30*60*1000&&cached.rows?.length){if(alive)setData({loading:false,rows:cached.rows,cached:true});return}const date='2026-09-28';const spots=[['Ceremony · 3:30 PM',...wedding.ceremony.coordinates,15],['Reception · 6:00 PM',...wedding.reception.coordinates,18],['Reception · 8:30 PM',...wedding.reception.coordinates,21]];const rows=(await Promise.all(spots.map(async([label,lat,lon,h])=>{const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,precipitation_probability,weather_code,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FDenver&forecast_days=16`;const j=await fetch(u).then(r=>{if(!r.ok)throw new Error('weather');return r.json()});const stamp=`${date}T${String(h).padStart(2,'0')}:00`;const idx=j.hourly?.time?.indexOf(stamp)??-1;return idx>=0?{label,temp:Math.round(j.hourly.temperature_2m[idx]),rain:j.hourly.precipitation_probability[idx],wind:Math.round(j.hourly.wind_speed_10m[idx]),desc:codeText[j.hourly.weather_code[idx]]||'Weather'}:null}))).filter(Boolean);if(rows.length)localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),rows}));if(alive)setData({loading:false,rows})}catch(e){try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(alive)setData({loading:false,rows:cached?.rows||[],cached:Boolean(cached?.rows?.length)})}catch{if(alive)setData({loading:false,rows:[]})}}}run();return()=>{alive=false}},[]);
  if(data.loading)return <Card><h3>Wedding-day weather</h3><p>Checking forecast availability…</p></Card>;
  if(!data.rows?.length)return <Card className="weather-wait paper-card"><span className="badge">WEATHER WATCH</span><h3>The exact wedding-day forecast is not available yet.</h3><p>Once September 28 enters the reliable forecast window, this page will automatically switch to time-specific conditions for the mountain ceremony and Denver reception.</p><p className="tiny">Mountain weather can change quickly. Bring a light layer even if Denver feels warm.</p></Card>;
  return <><div className="weather-grid">{data.rows.map(r=><Card key={r.label}><span className="badge">{data.cached?'SAVED FORECAST':'LIVE FORECAST'}</span><h3>{r.label}</h3><div className="temp">{r.temp}°F</div><p>{r.desc} · {r.rain}% precip · wind {r.wind} mph</p></Card>)}</div>{data.cached&&<p className="tiny center-note">Showing the most recent saved forecast while the app refreshes periodically.</p>}</>
}

function ColoradoQuiz({compact=false}){const [i,setI]=useState(0),[score,setScore]=useState(0),[picked,setPicked]=useState(null);const q=coloradoQuestions[i];const choose=n=>{if(picked!==null)return;setPicked(n);if(n===q.a)setScore(s=>s+1)};const next=()=>{if(i===coloradoQuestions.length-1){setI(0);setScore(0);setPicked(null)}else{setI(x=>x+1);setPicked(null)}};return <Card className="quiz"><span className="badge">GUESS THE COLORADO FACT</span><h3>{q.q}</h3><div className="quiz-choices">{q.choices.map((c,n)=><button key={c} onClick={()=>choose(n)} className={picked===null?'':n===q.a?'correct':n===picked?'wrong':''}>{c}</button>)}</div>{picked!==null&&<div className="fact"><b>{picked===q.a?'Correct! 🏔️':'Good guess!'}</b><p>{q.fact}</p><button className="button" onClick={next}>{i===coloradoQuestions.length-1?'Play again': 'Next fact'}</button></div>}{!compact&&<p className="tiny">Score: {score}/{coloradoQuestions.length}</p>}</Card>}

function Kids(){return <><PageHero title="Junior Wedding Explorers" sub="A real-world wedding adventure — no glitchy mini-game required"/><section className="page"><ExplorerChallenge/><BouquetCatch/><Card><h3>Photo scavenger hunt 📷</h3><p>Use a grown-up’s phone or the wedding disposable camera link and see how many you can spot.</p><div className="challenge-grid">{['Something blue','The biggest smile','Someone dancing funny','A beautiful flower','A Colorado mountain on a table sign','Someone wearing gold','The wedding cake','A family hug'].map(x=><span key={x}>📸 {x}</span>)}</div></Card><KidsThisOrThat/><ColoradoQuiz/></section></>}
function ExplorerChallenge(){const items=['Spot a blue flower','Find a mountain in the wedding décor','Dance through one whole song','Find someone who traveled from another state','Make someone in your family laugh','Spot a gold wedding detail','Find the cake or dessert table','Find a Colorado table-place sign','Take a silly family photo','Give the newlyweds a wave or high-five'];const [done,setDone]=useState(()=>JSON.parse(localStorage.getItem('wg-kids-challenge')||'[]'));useEffect(()=>localStorage.setItem('wg-kids-challenge',JSON.stringify(done)),[done]);const toggle=i=>setDone(d=>d.includes(i)?d.filter(x=>x!==i):[...d,i]);return <Card className="explorer-card"><span className="badge">WEDDING ADVENTURE CHALLENGE</span><h3>{done.length>=7?'Junior Wedding Explorer unlocked! 🏔️✨':`${done.length}/10 adventures complete`}</h3><div className="explorer-list">{items.map((x,i)=><button key={x} className={done.includes(i)?'done':''} onClick={()=>toggle(i)}><span>{done.includes(i)?'✓':'○'}</span>{x}</button>)}</div>{done.length>=7&&<div className="explorer-badge">🏅 JUNIOR WEDDING EXPLORER</div>}</Card>}
function KidsThisOrThat(){const qs=[['Who loves rock climbing and anime?','Londyn'],['Who loves golfing?','Miah'],['Where are Cory & Melinda getting married?','Sunrise Amphitheater'],['Where are the newlyweds heading after the wedding?','Costa Rica 🌴']];const [open,setOpen]=useState({});return <Card><span className="badge">OUR CREW + WEDDING TRIVIA</span><h3>Tap to reveal</h3><div className="reveal-list">{qs.map(([q,a],i)=><button key={q} onClick={()=>setOpen(v=>({...v,[i]:!v[i]}))}><b>{q}</b><span>{open[i]?a:'Tap for answer'}</span></button>)}</div></Card>}


function Tables(){
  const [query,setQuery]=useState('');
  const guestIndex=useMemo(()=>seatingChart.tables.flatMap(table=>table.guests.filter(name=>name!=='Open / Unassigned').map(name=>({name,table:table.number,place:table.place,image:table.image}))),[]);
  const q=query.trim().toLowerCase();
  const matches=q?guestIndex.filter(entry=>entry.name.toLowerCase().includes(q)):[];
  const chosen=matches.length===1?matches[0]:null;
  return <><PageHero title="Find My Table" sub="Assigned tables · choose any seat at your table"/><section className="page"><Card className="table-nine-card paper-card"><span className="badge">SEATING CHART</span><h3>Type your name. We’ll point you toward the mountain.</h3><p>Individual seats are not assigned — once you find your table, choose any open seat there.</p><label className="table-search"><span>Search by guest name</span><input type="search" autoComplete="name" placeholder="Start typing your name…" value={query} onChange={e=>setQuery(e.target.value)} /></label>{q&&<div className="search-results">{chosen?<div className="table-destination"><div className="table-destination-copy"><span className="badge">YOUR TABLE</span><h3>{chosen.name}</h3><strong>Table {chosen.table} · {chosen.place}</strong><p>Look for this Colorado table sign in the room. Choose any seat at your assigned table.</p></div><ImageLightbox src={chosen.image} alt={`Table ${chosen.table} ${chosen.place} sign`} caption={`Table ${chosen.table} · ${chosen.place}`} className="table-sign-preview"/></div>:matches.length>1?<><p className="tiny">A few names match. Tap yours:</p><div className="match-list">{matches.map(m=><button type="button" key={m.name} className="match-chip" onClick={()=>setQuery(m.name)}>{m.name}<span>Table {m.table}</span></button>)}</div></>:<p className="no-match">We don’t see that name yet. If your name is not on the seating chart, Table 9 is for you. 💙</p>}</div>}<div className="table-nine-callout"><b>Don’t see your name?</b><span>Table 9 · Royal Gorge is your fallback table.</span></div></Card><Card className="seating-chart-card"><ImageLightbox src={seatingChart.image} alt="City Park Pavilion seating chart showing Tables 1 through 9 and guest assignments" caption="Tap to enlarge the full seating chart" className="seating-chart-button"/></Card><SectionTitle eyebrow="Colorado Tables" title="Look for your landmark" sub="Each table is named for a Colorado place, with its matching sign displayed in the room."/><div className="place-grid seating-grid">{seatingChart.tables.map((table,i)=><Card key={table.number} className="table-place-card"><ImageLightbox src={table.image} alt={`Table ${table.number} ${table.place} sign`} className="mini-table-sign"/><span className="badge">TABLE {table.number}</span><h3>{table.place}</h3>{table.fallback?<p className="tiny"><b>Open / unassigned.</b> If you do not see your name on the chart, this table is for you.</p>:<p className="tiny">{table.guests.length} guests assigned</p>}{tablePlaces[i]&&tablePlaces[i][1]&&<p className="tiny">{tablePlaces[i][1]}</p>}</Card>)}</div></section></>
}

function Messages(){const [status,setStatus]=useState('');const submit=async e=>{e.preventDefault();setStatus('Sending…');const form=e.currentTarget;const body=new URLSearchParams(new FormData(form)).toString();try{const r=await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error();form.reset();setStatus('Message saved. Thank you for leaving us a little piece of the day. 💙')}catch{setStatus('That note did not send. Please try again or leave us a voice message instead.')}};return <><PageHero title="Messages of Love" sub="Sweet, funny, ridiculous or wise — we want to remember it"/><section className="page two-col"><Card><span className="badge">WRITE US A NOTE</span><h3>Say what you want us to read after the whirlwind</h3><form name="wedding-note" method="POST" data-netlify="true" onSubmit={submit} className="note-form"><input type="hidden" name="form-name" value="wedding-note"/><label>Your name<input name="name" required placeholder="Your name"/></label><label>Your message<textarea name="message" required rows="6" placeholder="A memory, advice, a joke, something sweet…"/></label><label>Favorite Cory & Melinda memory <textarea name="memory" rows="3"/></label><label>One piece of newlywed advice <textarea name="advice" rows="3"/></label><label className="capsule-check"><input type="checkbox" name="anniversary_capsule" value="yes"/> Save this one for our first-anniversary memory capsule</label><button className="button" type="submit">Send our note 💌</button>{status&&<p className="form-status">{status}</p>}</form></Card><Card><span className="badge">OR SAY IT OUT LOUD</span><h3>Leave a voice message 🎙️</h3><p>Tell a story, give advice, make us laugh, or leave something we can listen to again later.</p><External href={wedding.links.audioGuestbook}>Open the audio guestbook</External><hr/><h3>Share a photo too 📸</h3><p>Use our digital disposable camera to add your view of the day.</p><External href={wedding.links.disposableCamera} className="secondary">Open the wedding camera</External></Card></section></>}
function Gifts(){const [open,setOpen]=useState(false);const methods=[wedding.links.cashApp&&['Cash App',wedding.links.cashApp,'Open Cash App'],wedding.links.venmo&&['Venmo',wedding.links.venmo,'Open Venmo']].filter(Boolean);return <><PageHero title="Gifts & Well Wishes" sub="Your presence is the best gift"/><section className="page"><Card className="gift-card"><span className="badge">COSTA RICA HONEYMOON FUND</span><h3>Help us make a few more memories 🌴</h3><p>Celebrating with us is more than enough. For those who have asked about contributing toward our next adventure, we created one simple place to do it.</p>{methods.length?<button className="button gift-open" type="button" onClick={()=>setOpen(true)}>Send a Honeymoon Gift</button>:<p className="gift-coming">Honeymoon-fund options will be added here soon.</p>}<p className="tiny gift-no-pressure">No gift is expected — we’re just happy you’re here.</p><div className="honeymoon-mini"><b>Next adventure: Costa Rica 🌴</b><span>{weekend.honeymoon.publicNote}</span></div></Card><Card><h3>Prefer words instead?</h3><p>A note, a memory or a voice message will mean just as much to us.</p><AppLink to="/messages">Leave a message</AppLink></Card></section>{open&&<div className="gift-modal-layer" role="dialog" aria-modal="true" aria-label="Honeymoon gift options"><button className="gift-modal-scrim" aria-label="Close gift options" onClick={()=>setOpen(false)}/><div className="gift-modal"><button className="gift-modal-close" type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button><span className="badge">HONEYMOON FUND</span><h2>Send a little adventure our way</h2><p>Choose whichever option is easiest for you. Our payment usernames stay off the wedding site itself.</p><div className="gift-methods">{methods.map(([name,href,label])=><a key={name} href={href} target="_blank" rel="noreferrer" className="gift-method"><span><b>{name}</b><small>{label}</small></span><strong>→</strong></a>)}</div><p className="tiny">Your payment app may display its own account information after you leave the Wedding Hub.</p></div></div>}</>}
function Snack(){return <><PageHero title="Late-Night Snack" sub="Passport secret"/><section className="page"><Card><h3>Unlock at 7 Passport stamps</h3><p>Late-night snacks arrive at 9:30 PM — head to the snack station and refuel before the final dance-floor stretch.</p></Card></section></>}
function More(){return <><PageHero title="More to Explore" sub="Activities, people & guest favorites"/><section className="page tile-grid">{[["/know-before-you-go","Know Before You Go"],["/weekend","Wedding Weekend"],["/honeymoon","Costa Rica 🌴"],["/family","Our Crew"],["/wedding-party","Our People"],["/thank-you","A Note From Us"],["/kids","Junior Wedding Explorers"],["/messages","Messages of Love"],["/gifts","Gifts & Well Wishes"],["/weather-parking","Weather + Parking"],["/drinks","Drinks + Dessert"],["/tables","Find My Table"],["/snack","Snack Secret"]].map(([t,l])=><Link className="info-tile" to={t} key={t}><b>{l}</b><span>Open →</span></Link>)}</section><section className="page team-access-wrap"><Link className="team-access" to="/day-of">Day-of team access</Link></section></>}

function PrivateDayOf({view='home'}){
  const navigate=useNavigate();
  const [code,setCode]=useState(()=>sessionStorage.getItem('wg-private-code')||'');
  const [draft,setDraft]=useState('');
  const [data,setData]=useState(null);
  const [error,setError]=useState('');
  const [loading,setLoading]=useState(false);
  const load=async(pass)=>{setLoading(true);setError('');try{const r=await fetch('/.netlify/functions/private-dashboard',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:pass})});if(!r.ok){let msg='Private dashboard could not be opened.';if(r.status===401)msg='That access code is not correct.';else if(r.status===404)msg='Private function was not deployed. Check Netlify Functions.';else if(r.status===503)msg='The private passcode is not available to the deployed function yet. Redeploy after setting the Netlify environment variable.';else if(r.status>=500)msg='The private dashboard function returned a server error.';throw new Error(msg)}const j=await r.json();sessionStorage.setItem('wg-private-code',pass);sessionStorage.setItem('wg-private-data',JSON.stringify(j));setCode(pass);setData(j)}catch(e){const cached=sessionStorage.getItem('wg-private-data');const savedCode=sessionStorage.getItem('wg-private-code');if(cached&&savedCode===pass){try{setData(JSON.parse(cached));setCode(pass);setError('Offline copy loaded. Reconnect for the newest private updates.')}catch{setError(e.message)}}else{setError(e.message);sessionStorage.removeItem('wg-private-code');sessionStorage.removeItem('wg-private-data');setCode('')}}finally{setLoading(false)}};
  useEffect(()=>{if(code&&!data)load(code)},[]);
  if(!data)return <><PageHero title="Day-of Team" sub="Bride · Groom · Ceremony · Reception"/><section className="page"><Card className="private-login paper-card"><span className="badge">PRIVATE PLANNING AREA</span><h3>Enter the day-of access code</h3><p>This area is intentionally kept out of the main guest navigation. Vendor contacts and private logistics are served only after access is verified.</p><label>Access code<input type="password" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&draft&&load(draft)} /></label>{error&&<p className="private-error">{error}</p>}<button className="button" disabled={!draft||loading} onClick={()=>load(draft)}>{loading?'Checking…':'Open day-of pages'}</button></Card></section></>;
  const allSections=[['home','Overview','/day-of'],['vendors','Vendors','/day-of/vendors'],['money','Couple Money','/day-of/money'],['bride','Bride','/day-of/bride'],['groom','Groom','/day-of/groom'],['ceremony','Ceremony Coord','/day-of/ceremony'],['reception','Reception Coord','/day-of/reception'],['dj','DJ Sheet','/day-of/dj'],['officiant','Officiant Sheet','/day-of/officiant']];const sections=allSections.filter(([id])=>id==='home'||data[id]);
  const current=view==='home'?null:data[view];
  const lock=()=>{sessionStorage.removeItem('wg-private-code');sessionStorage.removeItem('wg-private-data');setCode('');setData(null)};
  return <><PageHero title={view==='home'?'Day-of Team Dashboard':current?.title||'Day-of Team'} sub="Private planning area"/><section className="page private-page">{error&&<p className="offline-private-note">{error}</p>}<div className="private-tabs">{sections.map(([id,label,to])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(to)}>{label}</button>)}</div>{view==='home'?<PrivateOverview data={data}/>:<PrivateSection data={current}/>}<button className="team-access" onClick={lock}>Lock private area</button></section></>
}

function PrivateOverview({data}){return <><Card className="paper-card"><span className="badge">MASTER DAY-OF BINDER</span><h3>3:30 ceremony → 4:45 early arrivals → 5:00 cocktails → 6:00 entrance → 6:20 dinner</h3><p>The private area combines the vendor directory, bride/groom guides, ceremony and reception coordinator binders, printable DJ/MC cue sheet and Bertram’s officiant speaking sheet.</p><p className="tiny">Allow roughly 50–65 minutes door-to-door between Flagstaff Mountain and City Park as a planning buffer, then recheck actual Monday traffic on the wedding day.</p><div className="access-level"><b>{data.accessLevel==='couple'?'Couple access':'Wedding-team access'}</b><span>{data.accessLevel==='couple'?'Bride/groom payment details are visible.':'Payment amounts are intentionally hidden at this access level.'}</span></div></Card><Card className="help-card"><span className="badge">NEED HELP NOW?</span><h3>Open the right person fast</h3><p><b>Ceremony / mountain issue:</b> Nessa Dover. <b>Reception / setup issue:</b> Tammy Murrie. <b>Music / announcement issue:</b> Michael Lancaster.</p><div className="actions"><AppLink to="/day-of/vendors">Open vendor directory</AppLink><AppLink to="/day-of/ceremony" className="secondary">Ceremony sheet</AppLink><AppLink to="/day-of/reception" className="secondary">Reception sheet</AppLink></div></Card><div className="tile-grid private-launch-grid">{([['Vendor Directory','/day-of/vendors'],...(data.money?[['Couple Money + Payments','/day-of/money']]:[]),['Bride','/day-of/bride'],['Groom','/day-of/groom'],['Ceremony Coordinator','/day-of/ceremony'],['Reception Coordinator','/day-of/reception'],['Print DJ / MC Sheet','/day-of/dj'],['Print Officiant Sheet','/day-of/officiant']]).map(([l,to])=><Link className="info-tile" to={to} key={to}><b>{l}</b><span>Open binder section →</span></Link>)}</div>{data.finalDecisions&&<Card><span className="badge">FINAL DECISIONS + OPEN ITEMS</span><h3>What is locked vs. what still needs an answer</h3><div className="decision-grid">{data.finalDecisions.map(x=><div className={'decision-item '+(x.status.startsWith('FINAL')?'final':'open')} key={x.item}><b>{x.item}</b><span>{x.status}</span><small>{x.detail}</small></div>)}</div></Card>}{data.masterChecklist&&<Card><h3>Critical binder assignments</h3><ul>{data.masterChecklist.map(x=><li key={x}>{x}</li>)}</ul></Card>}{data.note&&<Card><h3>Private-data status</h3><p>{data.note}</p></Card>}</>}

function PrivateQuickCue({timeline}){
  if(!timeline?.length)return null;
  const timed=timeline.map((x,i)=>({...x,i,mins:parseEventMinutes(x.time)})).filter(x=>x.mins!==null);
  const weddingDay=isWeddingDayDenver();
  const nowMins=denverClock().minutes;
  let current=null,next=null;
  if(weddingDay){for(const x of timed){if(x.mins<=nowMins)current=x;else{next=x;break}}}else{current=timed[0]||timeline[0];next=timed[1]||timeline[1]}
  return <Card className="quick-cue"><span className="badge">QUICK MODE</span><div className="quick-cue-grid"><div><small>{weddingDay?'NOW / MOST RECENT':'FIRST CUE'}</small><b>{current?.time||'—'}</b><strong>{current?.item||'Open the timeline below'}</strong>{current?.note&&<span>{current.note}</span>}</div><div><small>NEXT</small><b>{next?.time||'—'}</b><strong>{next?.item||'No later timed cue'}</strong>{next?.note&&<span>{next.note}</span>}</div></div></Card>
}

function PrivateSection({data}){if(!data)return <Card><h3>Section not configured</h3></Card>;return <div className="print-sheet"><div className="print-actions"><button className="button secondary" onClick={()=>window.print()}>Print this sheet</button></div><PrivateQuickCue timeline={data.timeline}/>{data.summary&&<Card className="paper-card"><p>{data.summary}</p></Card>}{data.timeline&&<Card><h3>Timeline</h3><div className="private-timeline">{data.timeline.map(x=><div key={x.time+x.item}><time>{x.time}</time><div><b>{x.item}</b>{x.note&&<span>{x.note}</span>}</div></div>)}</div></Card>}{data.processional&&<Card><h3>Processional order</h3><ol className="pretty-list">{data.processional.map(x=><li key={x}>{x}</li>)}</ol></Card>}{data.music&&<Card><h3>Music cue sheet</h3><div className="cue-table">{data.music.map(x=><div key={x.cue}><b>{x.cue}</b><span>{x.song}</span><small>{x.who}</small></div>)}</div></Card>}{data.ceremonyOrder&&<Card><h3>Ceremony order</h3><ol className="pretty-list">{data.ceremonyOrder.map(x=><li key={x}>{x}</li>)}</ol></Card>}{data.introductions&&<Card><h3>Grand entrance introduction order</h3><ol className="pretty-list introduction-list">{data.introductions.map(x=><li key={x}>{x}</li>)}</ol></Card>}{data.speaking&&<Card className="officiant-card"><h3>Officiant speaking outline</h3><div className="speaking-sheet">{data.speaking.map(x=><section key={x.heading}><h4>{x.heading}</h4><p>{x.text}</p></section>)}</div></Card>}{data.decor&&<DecorBinder decor={data.decor}/>} {data.food&&<Card><h3>Food + delivery plan</h3>{data.food.map(x=><div className="vendor-row" key={x.item}><div><b>{x.item}</b><span>{x.detail}</span></div><div><span>{x.status}</span></div></div>)}</Card>}{data.florals&&<FloralBinder florals={data.florals}/>} {data.setup&&<Card><h3>Setup + reminders</h3><ul>{data.setup.map(x=><li key={x}>{x}</li>)}</ul></Card>}{data.vendors&&<Card><h3>Vendors + contacts</h3>{data.vendors.map(v=><div className="vendor-row" key={v.role+v.name}><div><b>{v.role}</b><span>{v.name||'Vendor name still needed'}</span>{v.notes&&<small>{v.notes}</small>}</div><div>{v.status&&<span><b>{v.status}</b></span>}{v.arrival&&<span>{v.arrival}</span>}{v.phone&&<a href={`tel:${v.phone}`}>{v.phone}</a>}{v.email&&<a href={`mailto:${v.email}`}>{v.email}</a>}{!v.phone&&!v.email&&<span className="tiny">Private contact not loaded</span>}</div></div>)}</Card>}{data.actionItems&&<Card><h3>Vendor / planning action items</h3><ul>{data.actionItems.map(x=><li key={x}>{x}</li>)}</ul></Card>}{data.payments&&<Card className="money-due"><h3>Money due / payment check</h3><ul>{data.payments.map(x=><li key={x}>{x}</li>)}</ul></Card>}{data.reminders&&<Card><h3>Reminders</h3><ul>{data.reminders.map(x=><li key={x}>{x}</li>)}</ul></Card>}</div>}

function DecorBinder({decor}){const groups=[['Guest Tables',decor.guestTables],['Sweetheart Table',decor.sweetheart],['Welcome Area',decor.welcome],['Cake Table',decor.cake],['Buffet / Food Tables',decor.buffet]].filter(x=>x[1]);return <Card><h3>Reception décor setup binder</h3><div className="decor-grid">{groups.map(([title,items])=><section key={title}><h4>{title}</h4><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></section>)}</div>{decor.inspirationImages&&<><h4>Current wedding-sign visual references</h4><div className="binder-images">{decor.inspirationImages.map(x=><figure key={x.path}><img src={x.path} alt={x.label} loading="lazy" decoding="async"/><figcaption>{x.label}</figcaption></figure>)}</div></>}{decor.visualAssets&&<><h4>Table setup visual references</h4><div className="asset-grid">{decor.visualAssets.map(x=><VisualAsset asset={x} key={x.file}/>)}</div><p className="tiny">Current décor mockups and floral guides are included in this project. As the wedding gets closer, replace the final-setup placeholder with a real photo of the completed table so Tammy can match the boxed décor exactly.</p></>}</Card>}
function VisualAsset({asset}){return <div className="asset-slot">{asset.path?<ImageLightbox src={asset.path} alt={asset.label} className="asset-lightbox"/>:null}<b>{asset.label}</b><code>{asset.file}</code>{!asset.path&&asset.status&&<span>{asset.status}</span>}</div>}


function FloralBinder({florals}){return <><Card><h3>{florals.title}</h3><p>{florals.sourceNote}</p>{florals.visualAssets&&<div className="asset-grid">{florals.visualAssets.map(x=><VisualAsset asset={x} key={x.file}/>)}</div>}</Card><Card><h3>Bridal bouquet ordering guide</h3><div className="order-table">{florals.bouquetOrder.map(([f,n,s])=><div key={f}><b>{f}</b><span>{n}</span><small>{s}</small></div>)}</div></Card><Card><h3>Prep + how-to</h3><h4>Flower prep</h4><ol>{florals.prep.map(x=><li key={x}>{x}</li>)}</ol><h4>Assembly</h4><ol>{florals.assembly.map(x=><li key={x}>{x}</li>)}</ol></Card><Card><h3>Boutonnières + corsages / wearables</h3><ul>{florals.wearables.map(x=><li key={x}>{x}</li>)}</ul></Card></>}


function NotFound(){return <><PageHero title="That page wandered off the trail"/><section className="page"><AppLink to="/">Back home</AppLink></section></>}

export default function App(){return <Layout><Routes>
  <Route path="/" element={<Home/>}/><Route path="/schedule" element={<SchedulePage/>}/><Route path="/know-before-you-go" element={<KnowBeforeYouGo/>}/><Route path="/weekend" element={<WeddingWeekend/>}/><Route path="/honeymoon" element={<Honeymoon/>}/><Route path="/ceremony" element={<Ceremony/>}/><Route path="/reception" element={<Reception/>}/><Route path="/directions" element={<Directions/>}/><Route path="/passport" element={<Passport/>}/><Route path="/family" element={<Family/>}/><Route path="/wedding-party" element={<WeddingParty/>}/><Route path="/thank-you" element={<ThankYou/>}/><Route path="/drinks" element={<Drinks/>}/><Route path="/weather-parking" element={<WeatherParking/>}/><Route path="/kids" element={<Kids/>}/><Route path="/messages" element={<Messages/>}/><Route path="/gifts" element={<Gifts/>}/><Route path="/tables" element={<Tables/>}/><Route path="/snack" element={<Snack/>}/><Route path="/more" element={<More/>}/><Route path="/day-of" element={<PrivateDayOf view="home"/>}/><Route path="/day-of/vendors" element={<PrivateDayOf view="vendors"/>}/><Route path="/day-of/money" element={<PrivateDayOf view="money"/>}/><Route path="/day-of/bride" element={<PrivateDayOf view="bride"/>}/><Route path="/day-of/groom" element={<PrivateDayOf view="groom"/>}/><Route path="/day-of/ceremony" element={<PrivateDayOf view="ceremony"/>}/><Route path="/day-of/reception" element={<PrivateDayOf view="reception"/>}/><Route path="/day-of/dj" element={<PrivateDayOf view="dj"/>}/><Route path="/day-of/officiant" element={<PrivateDayOf view="officiant"/>}/><Route path="*" element={<NotFound/>}/>
</Routes></Layout>}
